POST http://localhost:3080/api/v1/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

###

GET http://localhost:3080/api/v1/clients?page=0&size=2&sort=name
Accept: application/json
Content-Type: application/json

###

POST http://localhost:3080/api/v1/clients
Accept: application/json
Content-Type: application/json

{
  "name": "Ana",
  "surname": "Costa",
  "age": 19
}

###

PUT http://localhost:3080/api/v1/clients
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "name": "Maria Carolina",
  "age": 35
}

###

GET http://localhost:3080/api/v1/swagger-ui-custom.html